added support for primitive wrappers to not be handled as objects
cujojs/jiff pull request #48
Opened 2023-11-21 18:13 UTC by jej2003

2023-11-21 18:13 UTC, jej2003 commented
closes #48

2023-11-27 18:50 UTC, jej2003 commented
@briancavalier , just checking in to see if there's anything that I can do to help move this forward?  Perhaps there is a better way to implement?

2023-11-28 13:04 UTC, briancavalier commented
Hey @jej2003 , thanks for the PR! I should have time today to take a look.

2023-11-29 13:25 UTC, briancavalier requested changes
Looks good! Just one minor suggestion.

2023-11-29 13:25 UTC, briancavalier commented on lib/clone.js
> +	if (typeof x === 'object' && x !== null && (x instanceof String || x instanceof Number || x instanceof Boolean)) {
I think we can simplify slightly: `instanceof` is sufficient, and the previous `if` rules out `null` and non-objects.

```suggestion
	if (x instanceof String || x instanceof Number || x instanceof Boolean) {
```

2023-11-30 13:39 UTC, jej2003 commented
@briancavalier agree and applied the requested change. Thanks!

2023-12-01 02:57 UTC, briancavalier approved these changes
Thanks @jej2003!

2023-12-01 02:57 UTC, merged

2023-12-01 03:09 UTC, briancavalier commented
I'll try to publish a new version in the next couple days.

2023-12-09 13:38 UTC, briancavalier commented
@jej2003 Apologies for not publishing a new version yet.

NPM support is helping us with an issue that's preventing us from publishing. I'll let you know when we've published a new version.